apiVersion : apps/v1
kind: Deployment
metadata:
  name: azure_devops_aks_deploy 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure_devops_aks_deploy
  template:
    metadata:
      labels:
        app: azure_devops_aks_deploy 
    spec:
      containers:
        - name: azure_devops_aks_deploy 
          image: azurehandson.azurecr.io/azure_devops_aks_deploy
          ports:
          - containerPort: 80