apiVersion : apps/v1
kind: Deployment
metadata:
  name: azure-devops-aks-deploy 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-devops-aks-deploy
  template:
    metadata:
      labels:
        app: azure-devops-aks-deploy 
    spec:
      containers:
        - name: azure-devops-aks-deploy 
          image: azurehandson.azurecr.io/azure_devops_aks_deploy
          ports:
          - containerPort: 80